apiVersion: v1
kind: Secret
metadata:
  name: fraud-secrets
type: Opaque
stringData:
  POSTGRES_USER: fraud
  POSTGRES_PASSWORD: fraud
  POSTGRES_DB: frauddb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-config
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  KAFKA_BROKER: kafka-service:9092
  KAFKA_TOPIC: transactions
  MLFLOW_TRACKING_URI: "sqlite:////app/mlflow.db"
  MODEL_NAME: fraud-model
  MODEL_PATH: "/app/model_export"
  MODEL_VERSION: "1"